version: 2
sources:
- name: museum_visit
  description: museum_visit 데이터셋의 테이블 모음
  database: museum_visit
  tables:
  - name: visitor
    description: 방문자에 대한 정보
    columns:
    - name: ID
      description: 고유 식별자
    - name: Name
      description: 이름
    - name: Level_of_membership
      description: 회원 등급
    - name: Age
      description: 나이
  - name: visit
    description: 방문 기록 테이블
    columns:
    - name: Museum_ID
      description: 박물관 고유 식별자
    - name: visitor_ID
      description: 방문객 고유 식별자
    - name: Num_of_Ticket
      description: 구매한 티켓 수
    - name: Total_spent
      description: 총 지출 금액
  - name: museum
    description: 박물관에 대한 설명
    columns:
    - name: Museum_ID
      description: 박물관의 고유 식별자
    - name: Name
      description: 박물관의 이름
    - name: Num_of_Staff
      description: 박물관의 직원 수
    - name: Open_Year
      description: 박물관의 개관 연도
