version: 2
sources:
- name: wedding
  description: wedding 데이터셋의 테이블 모음
  database: wedding
  tables:
  - name: wedding
    description: 결혼식 정보를 담고 있는 테이블
    columns:
    - name: Church_ID
      description: 교회의 고유 식별자
      tests:
      - unique
      - not_null
    - name: Male_ID
      description: 남성의 고유 식별자
      tests:
      - not_null
    - name: Female_ID
      description: 여성의 고유 식별자
      tests:
      - not_null
    - name: Year
      description: 결혼식이 열리는 연도
      tests:
      - not_null
  - name: people
    description: 사람들에 대한 정보
    columns:
    - name: People_ID
      description: 고유 식별자
      tests:
      - unique
      - not_null
    - name: Name
      description: 이름
      tests:
      - not_null
    - name: Country
      description: 국가
      tests:
      - not_null
    - name: Is_Male
      description: 성별
      tests:
      - not_null
    - name: Age
      description: 나이
      tests:
      - not_null
  - name: church
    description: 교회에 대한 설명
    columns:
    - name: Church_ID
      description: 교회의 고유 식별자
      tests:
      - unique
      - not_null
    - name: Name
      description: 교회의 이름
      tests:
      - not_null
    - name: Organized_by
      description: 교회를 조직한 사람
      tests:
      - not_null
    - name: Open_Date
      description: 교회의 개설 날짜
      tests:
      - not_null
    - name: Continuation_of
      description: 계속되는 조직
      tests:
      - not_null
