version: 2
sources:
- name: program_share
  description: program_share 데이터셋의 테이블 모음
  database: program_share
  tables:
  - name: program
    description: 프로그램에 대한 설명
    columns:
    - name: Program_ID
      description: 프로그램의 고유 식별자
    - name: Name
      description: 프로그램의 이름
    - name: Origin
      description: 프로그램의 출처
    - name: Launch
      description: 프로그램의 시작 시간
    - name: Owner
      description: 프로그램의 소유자
  - name: channel
    description: 채널에 대한 설명
    columns:
    - name: Channel_ID
      description: 채널의 고유 식별자
    - name: Name
      description: 채널 이름
    - name: Owner
      description: 채널 소유자
    - name: Share_in_percent
      description: 채널의 지분 비율
    - name: Rating_in_percent
      description: 채널의 평가 비율
  - name: broadcast
    description: 방송 테이블에 대한 설명
    columns:
    - name: Channel_ID
      description: 채널 식별자
    - name: Program_ID
      description: 프로그램 식별자
    - name: Time_of_day
      description: 방송 시간
  - name: broadcast_share
    description: 방송 점유율에 대한 정보
    columns:
    - name: Channel_ID
      description: 채널의 고유 식별자
    - name: Program_ID
      description: 프로그램의 고유 식별자
    - name: Date
      description: 방송 날짜
    - name: Share_in_percent
      description: 방송 점유율(퍼센트)
