version: 2
sources:
- name: icfp_1
  description: icfp_1 데이터셋의 테이블 모음
  database: icfp_1
  tables:
  - name: Papers
    description: 논문 테이블에 대한 설명
    columns:
    - name: paperID
      description: 논문의 고유 식별자
    - name: title
      description: 논문의 제목
  - name: Inst
    description: 인스턴스 테이블에 대한 설명
    columns:
    - name: instID
      description: 인스턴스 고유 식별자
    - name: name
      description: 이름 필드
    - name: country
      description: 국가 필드
  - name: Authors
    description: 저자에 대한 정보
    columns:
    - name: authID
      description: 저자의 고유 식별자
    - name: lname
      description: 저자의 성
    - name: fname
      description: 저자의 이름
  - name: Authorship
    description: 저자 정보 테이블
    columns:
    - name: authID
      description: 저자 고유 식별자
    - name: instID
      description: 기관 고유 식별자
    - name: paperID
      description: 논문 고유 식별자
    - name: authOrder
      description: 저자 순서
