version: 2
sources:
- name: department_store
  description: department_store 데이터셋의 테이블 모음
  database: department_store
  tables:
  - name: Customer_Addresses
    description: 고객 주소 정보를 저장하는 테이블
    columns:
    - name: customer_id
      description: 고객의 고유 식별자
    - name: address_id
      description: 주소의 고유 식별자
    - name: date_from
      description: 주소 유효 시작 날짜
    - name: date_to
      description: 주소 유효 종료 날짜
  - name: Products
    description: 제품에 대한 정보
    columns:
    - name: product_id
      description: 제품 고유 식별자
    - name: product_type_code
      description: 제품 유형 코드
    - name: product_name
      description: 제품 이름
    - name: product_price
      description: 제품 가격
  - name: Customers
    description: 고객 정보를 저장하는 테이블
    columns:
    - name: customer_id
      description: 고객의 고유 식별자
    - name: payment_method_code
      description: 고객의 결제 방법 코드
    - name: customer_code
      description: 고객 코드
    - name: customer_name
      description: 고객 이름
    - name: customer_address
      description: 고객 주소
    - name: customer_phone
      description: 고객 전화번호
    - name: customer_email
      description: 고객 이메일
  - name: Department_Stores
    description: 부서 상점에 대한 설명
    columns:
    - name: dept_store_id
      description: 부서 상점의 고유 식별자
    - name: dept_store_chain_id
      description: 부서 상점 체인의 고유 식별자
    - name: store_name
      description: 상점 이름
    - name: store_address
      description: 상점 주소
    - name: store_phone
      description: 상점 전화번호
    - name: store_email
      description: 상점 이메일 주소
  - name: Order_Items
    description: 주문 항목에 대한 정보
    columns:
    - name: order_item_id
      description: 주문 항목의 고유 식별자
    - name: order_id
      description: 주문과 연결된 고유 식별자
    - name: product_id
      description: 제품의 고유 식별자
  - name: Departments
    description: 부서에 대한 정보
    columns:
    - name: department_id
      description: 부서 고유 식별자
    - name: dept_store_id
      description: 부서가 속한 매장 고유 식별자
    - name: department_name
      description: 부서 이름
  - name: Addresses
    description: 주소 정보를 저장하는 테이블
    columns:
    - name: address_id
      description: 주소의 고유 식별자
    - name: address_details
      description: 주소의 상세 정보
  - name: Supplier_Addresses
    description: 공급업체 주소에 대한 정보
    columns:
    - name: supplier_id
      description: 공급업체 고유 식별자
    - name: address_id
      description: 주소 고유 식별자
    - name: date_from
      description: 주소 유효 시작 날짜
    - name: date_to
      description: 주소 유효 종료 날짜
  - name: Staff
    description: 직원 정보를 담고 있는 테이블
    columns:
    - name: staff_id
      description: 직원 고유 식별자
    - name: staff_gender
      description: 직원 성별
    - name: staff_name
      description: 직원 이름
  - name: Staff_Department_Assignments
    description: 직원 부서 할당에 대한 정보
    columns:
    - name: staff_id
      description: 직원의 고유 식별자
    - name: department_id
      description: 부서의 고유 식별자
    - name: date_assigned_from
      description: 할당 시작 날짜
    - name: job_title_code
      description: 직무 제목 코드
    - name: date_assigned_to
      description: 할당 종료 날짜
  - name: Customer_Orders
    description: 고객 주문에 대한 정보
    columns:
    - name: order_id
      description: 주문 고유 식별자
    - name: customer_id
      description: 고객 고유 식별자
    - name: order_status_code
      description: 주문 상태 코드
    - name: order_date
      description: 주문 날짜
  - name: Product_Suppliers
    description: 제품 공급자에 대한 정보
    columns:
    - name: product_id
      description: 제품의 고유 식별자
    - name: supplier_id
      description: 공급자의 고유 식별자
    - name: date_supplied_from
      description: 공급 시작 날짜
    - name: date_supplied_to
      description: 공급 종료 날짜
    - name: total_amount_purchased
      description: 구매한 총 수량
    - name: total_value_purchased
      description: 구매한 총 금액
  - name: Department_Store_Chain
    description: 부서 상점 체인에 대한 설명
    columns:
    - name: dept_store_chain_id
      description: 부서 상점 체인의 고유 식별자
    - name: dept_store_chain_name
      description: 부서 상점 체인의 이름
  - name: Suppliers
    description: 공급업체에 대한 정보
    columns:
    - name: supplier_id
      description: 공급업체 고유 식별자
    - name: supplier_name
      description: 공급업체 이름
    - name: supplier_phone
      description: 공급업체 전화번호
