version: 2
sources:
- name: restaurants
  description: restaurants 데이터셋의 테이블 모음
  database: restaurants
  tables:
  - name: RESTAURANT
    description: 레스토랑에 대한 정보
    columns:
    - name: ID
      description: 고유 식별자
    - name: NAME
      description: 레스토랑 이름
    - name: FOOD_TYPE
      description: 음식 종류
    - name: CITY_NAME
      description: 도시 이름
    - name: RATING
      description: 평점
  - name: LOCATION
    description: 위치 정보를 담고 있는 테이블
    columns:
    - name: RESTAURANT_ID
      description: 레스토랑의 고유 식별자
    - name: HOUSE_NUMBER
      description: 집 번호
    - name: STREET_NAME
      description: 거리 이름
    - name: CITY_NAME
      description: 도시 이름
