version: 2
sources:
- name: club_1
  description: club_1 데이터셋의 테이블 모음
  database: club_1
  tables:
  - name: Member_of_club
    description: 클럽 회원에 대한 정보
    columns:
    - name: StuID
      description: 학생 고유 식별자
      tests:
      - unique
      - not_null
    - name: ClubID
      description: 클럽 고유 식별자
      tests:
      - not_null
    - name: Position
      description: 회원의 직책
      tests:
      - not_null
  - name: Student
    description: 학생 정보를 담고 있는 테이블
    columns:
    - name: StuID
      description: 학생 고유 식별자
      tests:
      - unique
      - not_null
    - name: LName
      description: 학생의 성
      tests:
      - not_null
    - name: Fname
      description: 학생의 이름
      tests:
      - not_null
    - name: Age
      description: 학생의 나이
      tests:
      - not_null
    - name: Sex
      description: 학생의 성별
      tests:
      - not_null
    - name: Major
      description: 학생의 전공
      tests:
      - not_null
    - name: Advisor
      description: 학생의 지도교수 ID
      tests:
      - not_null
    - name: city_code
      description: 학생의 도시 코드
      tests:
      - not_null
  - name: Club
    description: 클럽에 대한 설명
    columns:
    - name: ClubID
      description: 클럽의 고유 식별자
      tests:
      - unique
      - not_null
    - name: ClubName
      description: 클럽의 이름
      tests:
      - not_null
    - name: ClubDesc
      description: 클럽에 대한 설명
      tests:
      - not_null
    - name: ClubLocation
      description: 클럽의 위치
      tests:
      - not_null
