version: 2
sources:
- name: election_representative
  description: election_representative 데이터셋의 테이블 모음
  database: election_representative
  tables:
  - name: election
    description: 선거에 대한 정보
    columns:
    - name: Election_ID
      description: 선거 고유 식별자
      tests:
      - unique
      - not_null
    - name: Representative_ID
      description: 대표자 고유 식별자
      tests:
      - not_null
    - name: Date
      description: 선거 날짜
      tests:
      - not_null
    - name: Votes
      description: 투표 수
      tests:
      - not_null
    - name: Vote_Percent
      description: 투표 비율
      tests:
      - not_null
    - name: Seats
      description: 의석 수
      tests:
      - not_null
    - name: Place
      description: 장소
      tests:
      - not_null
  - name: representative
    description: 대표자에 대한 정보
    columns:
    - name: Representative_ID
      description: 대표자 고유 식별자
      tests:
      - unique
      - not_null
    - name: Name
      description: 대표자 이름
      tests:
      - not_null
    - name: State
      description: 대표자가 속한 주
      tests:
      - not_null
    - name: Party
      description: 대표자가 소속된 정당
      tests:
      - not_null
    - name: Lifespan
      description: 대표자의 생애 종료일
      tests:
      - not_null
