version: 2
sources:
- name: party_host
  description: party_host 데이터셋의 테이블 모음
  database: party_host
  tables:
  - name: host
    description: 호스트에 대한 설명
    columns:
    - name: Host_ID
      description: 호스트의 고유 식별자
      tests:
      - unique
      - not_null
    - name: Name
      description: 호스트의 이름
      tests:
      - not_null
    - name: Nationality
      description: 호스트의 국적
      tests:
      - not_null
    - name: Age
      description: 호스트의 나이
      tests:
      - not_null
  - name: party_host
    description: 파티 주최자에 대한 정보
    columns:
    - name: Party_ID
      description: 파티의 고유 식별자
      tests:
      - unique
      - not_null
    - name: Host_ID
      description: 주최자의 고유 식별자
      tests:
      - not_null
    - name: Is_Main_in_Charge
      description: 주최자가 주 책임자인지 여부
      tests:
      - not_null
  - name: party
    description: 파티에 대한 정보
    columns:
    - name: Party_ID
      description: 파티의 고유 식별자
      tests:
      - unique
      - not_null
    - name: Party_Theme
      description: 파티의 주제
      tests:
      - not_null
    - name: Location
      description: 파티의 장소
      tests:
      - not_null
    - name: First_year
      description: 파티의 시작 연도
      tests:
      - not_null
    - name: Last_year
      description: 파티의 종료 연도
      tests:
      - not_null
    - name: Number_of_hosts
      description: 호스트의 수
      tests:
      - not_null
