version: 2
sources:
- name: activity_1
  description: activity_1 데이터셋의 테이블 모음
  database: activity_1
  tables:
  - name: Activity
    description: 활동 테이블에 대한 설명
    columns:
    - name: actid
      description: 활동의 고유 식별자
      tests:
      - unique
      - not_null
    - name: activity_name
      description: 활동의 이름
      tests:
      - not_null
  - name: Participates_in
    description: 참여하는 활동에 대한 정보
    columns:
    - name: stuid
      description: 학생의 고유 식별자
      tests:
      - unique
      - not_null
    - name: actid
      description: 활동의 고유 식별자
      tests:
      - not_null
  - name: Faculty_Participates_in
    description: 교수 참여 테이블
    columns:
    - name: FacID
      description: 교수의 고유 식별자
      tests:
      - unique
      - not_null
    - name: actid
      description: 활동의 고유 식별자
      tests:
      - not_null
  - name: Student
    description: 학생 테이블에 대한 설명
    columns:
    - name: StuID
      description: 학생 고유 식별자
      tests:
      - unique
      - not_null
    - name: LName
      description: 학생의 성
      tests:
      - not_null
    - name: Fname
      description: 학생의 이름
      tests:
      - not_null
    - name: Age
      description: 학생의 나이
      tests:
      - not_null
    - name: Sex
      description: 학생의 성별
      tests:
      - not_null
    - name: Major
      description: 전공 코드
      tests:
      - not_null
    - name: Advisor
      description: 지도 교수 코드
      tests:
      - not_null
    - name: city_code
      description: 도시 코드
      tests:
      - not_null
  - name: Faculty
    description: 교수진에 대한 정보
    columns:
    - name: FacID
      description: 교수 고유 식별자
      tests:
      - unique
      - not_null
    - name: Lname
      description: 성
      tests:
      - not_null
    - name: Fname
      description: 이름
      tests:
      - not_null
    - name: Rank
      description: 직급
      tests:
      - not_null
    - name: Sex
      description: 성별
      tests:
      - not_null
    - name: Phone
      description: 전화번호
      tests:
      - not_null
    - name: Room
      description: 방 번호
      tests:
      - not_null
    - name: Building
      description: 건물 이름
      tests:
      - not_null
