version: 2
sources:
- name: perpetrator
  description: perpetrator 데이터셋의 테이블 모음
  database: perpetrator
  tables:
  - name: perpetrator
    description: 가해자에 대한 정보
    columns:
    - name: Perpetrator_ID
      description: 가해자의 고유 식별자
    - name: People_ID
      description: 사람의 고유 식별자
    - name: Date
      description: 사건 발생 일시
    - name: Year
      description: 사건 발생 연도
    - name: Location
      description: 사건 발생 장소
    - name: Country
      description: 사건 발생 국가
    - name: Killed
      description: 사건에서 사망한 인원 수
    - name: Injured
      description: 사건에서 부상당한 인원 수
  - name: people
    description: 사람들에 대한 정보
    columns:
    - name: People_ID
      description: 고유 식별자
    - name: Name
      description: 이름
    - name: Height
      description: 신장
    - name: Weight
      description: 체중
    - name: Home Town
      description: 고향
