version: 2
sources:
- name: course_teach
  description: course_teach 데이터셋의 테이블 모음
  database: course_teach
  tables:
  - name: course
    description: 강좌에 대한 정보
    columns:
    - name: Course_ID
      description: 강좌의 고유 식별자
    - name: Staring_Date
      description: 강좌 시작 날짜
    - name: Course
      description: 강좌 이름
  - name: teacher
    description: 교사에 대한 정보
    columns:
    - name: Teacher_ID
      description: 교사의 고유 식별자
    - name: Name
      description: 교사의 이름
    - name: Age
      description: 교사의 나이
    - name: Hometown
      description: 교사의 고향
  - name: course_arrange
    description: 강좌 배치에 대한 설명
    columns:
    - name: Course_ID
      description: 강좌의 고유 식별자
    - name: Teacher_ID
      description: 교사의 고유 식별자
    - name: Grade
      description: 학년
