version: 2
sources:
- name: epinions_1
  description: epinions_1 데이터셋의 테이블 모음
  database: epinions_1
  tables:
  - name: review
    description: 리뷰 테이블에 대한 설명
    columns:
    - name: a_id
      description: 작성자 ID
    - name: u_id
      description: 사용자 ID
    - name: i_id
      description: 아이템 ID
    - name: rating
      description: 평점
    - name: rank
      description: 순위
  - name: trust
    description: 신뢰 관계를 나타내는 테이블
    columns:
    - name: source_u_id
      description: 신뢰를 제공하는 사용자 ID
    - name: target_u_id
      description: 신뢰를 받는 사용자 ID
    - name: trust
      description: 신뢰의 정도
  - name: useracct
    description: 사용자 계정 정보를 저장하는 테이블
    columns:
    - name: u_id
      description: 사용자 고유 ID
    - name: name
      description: 사용자 이름
  - name: item
    description: 아이템 테이블에 대한 설명
    columns:
    - name: i_id
      description: 아이템 고유 식별자
    - name: title
      description: 아이템 제목
