version: 2
sources:
- name: journal_committee
  description: journal_committee 데이터셋의 테이블 모음
  database: journal_committee
  tables:
  - name: editor
    description: 편집자에 대한 정보
    columns:
    - name: Editor_ID
      description: 편집자의 고유 식별자
      tests:
      - unique
      - not_null
    - name: Name
      description: 편집자의 이름
      tests:
      - not_null
    - name: Age
      description: 편집자의 나이
      tests:
      - not_null
  - name: journal
    description: 저널 테이블에 대한 설명
    columns:
    - name: Journal_ID
      description: 저널의 고유 식별자
      tests:
      - unique
      - not_null
    - name: Date
      description: 저널의 날짜 및 시간
      tests:
      - not_null
    - name: Theme
      description: 저널의 주제
      tests:
      - not_null
    - name: Sales
      description: 저널의 판매량
      tests:
      - not_null
  - name: journal_committee
    description: 저널 위원회에 대한 설명
    columns:
    - name: Editor_ID
      description: 편집자 식별자
      tests:
      - unique
      - not_null
    - name: Journal_ID
      description: 저널 식별자
      tests:
      - unique
      - not_null
    - name: Work_Type
      description: 작업 유형
      tests:
      - not_null
