version: 2
sources:
- name: book_2
  description: book_2 데이터셋의 테이블 모음
  database: book_2
  tables:
  - name: book
    description: 책에 대한 정보
    columns:
    - name: Book_ID
      description: 책의 고유 식별자
    - name: Title
      description: 책 제목
    - name: Issues
      description: 문제 수
    - name: Writer
      description: 저자
  - name: publication
    description: 출판물에 대한 정보
    columns:
    - name: Publication_ID
      description: 출판물 고유 식별자
    - name: Book_ID
      description: 책 고유 식별자
    - name: Publisher
      description: 출판사 이름
    - name: Publication_Date
      description: 출판 날짜
    - name: Price
      description: 출판물 가격
