version: 2
sources:
- name: club_1
  description: club_1 데이터셋의 테이블 모음
  database: club_1
  tables:
  - name: Member_of_club
    description: 클럽 회원에 대한 정보
    columns:
    - name: StuID
      description: 학생 고유 식별자
    - name: ClubID
      description: 클럽 고유 식별자
    - name: Position
      description: 회원의 직책
  - name: Student
    description: 학생 정보를 담고 있는 테이블
    columns:
    - name: StuID
      description: 학생 고유 식별자
    - name: LName
      description: 학생의 성
    - name: Fname
      description: 학생의 이름
    - name: Age
      description: 학생의 나이
    - name: Sex
      description: 학생의 성별
    - name: Major
      description: 학생의 전공
    - name: Advisor
      description: 학생의 지도교수 ID
    - name: city_code
      description: 학생의 도시 코드
  - name: Club
    description: 클럽에 대한 설명
    columns:
    - name: ClubID
      description: 클럽의 고유 식별자
    - name: ClubName
      description: 클럽의 이름
    - name: ClubDesc
      description: 클럽에 대한 설명
    - name: ClubLocation
      description: 클럽의 위치
