version: 2
sources:
- name: manufactory_1
  description: manufactory_1 데이터셋의 테이블 모음
  database: manufactory_1
  tables:
  - name: Products
    description: 제품에 대한 정보
    columns:
    - name: Code
      description: 제품 코드
      tests:
      - unique
      - not_null
    - name: Name
      description: 제품 이름
      tests:
      - not_null
    - name: Price
      description: 제품 가격
      tests:
      - not_null
    - name: Manufacturer
      description: 제조사 ID
      tests:
      - not_null
  - name: Manufacturers
    description: 제조업체에 대한 정보
    columns:
    - name: Code
      description: 제조업체 코드
      tests:
      - unique
      - not_null
    - name: Name
      description: 제조업체 이름
      tests:
      - not_null
    - name: Headquarter
      description: 본사 위치
      tests:
      - not_null
    - name: Founder
      description: 창립자 이름
      tests:
      - not_null
    - name: Revenue
      description: 연간 수익
      tests:
      - not_null
