version: 2
sources:
- name: architecture
  description: architecture 데이터셋의 테이블 모음
  database: architecture
  tables:
  - name: architect
    description: 건축가에 대한 정보
    columns:
    - name: id
      description: 고유 식별자
    - name: name
      description: 이름
    - name: nationality
      description: 국적
    - name: gender
      description: 성별
  - name: mill
    description: 밀에 대한 설명
    columns:
    - name: architect_id
      description: 건축가 식별자
    - name: id
      description: 고유 식별자
    - name: location
      description: 위치
    - name: name
      description: 밀 이름
    - name: type
      description: 밀 유형
    - name: built_year
      description: 건축 연도
    - name: notes
      description: 비고
  - name: bridge
    description: 다리 테이블에 대한 설명
    columns:
    - name: architect_id
      description: 건축가 식별자
    - name: id
      description: 고유 식별자
    - name: name
      description: 다리 이름
    - name: location
      description: 위치
    - name: length_meters
      description: 길이(미터)
    - name: length_feet
      description: 길이(피트)
