version: 2
sources:
- name: ship_1
  description: ship_1 데이터셋의 테이블 모음
  database: ship_1
  tables:
  - name: captain
    description: 선장의 정보를 담고 있는 테이블
    columns:
    - name: Captain_ID
      description: 선장 고유 식별자
    - name: Name
      description: 선장 이름
    - name: Ship_ID
      description: 선장이 소속된 배의 고유 식별자
    - name: age
      description: 선장의 나이
    - name: Class
      description: 선장의 클래스
    - name: Rank
      description: 선장의 직급
  - name: Ship
    description: 선박에 대한 정보
    columns:
    - name: Ship_ID
      description: 선박의 고유 식별자
    - name: Name
      description: 선박의 이름
    - name: Type
      description: 선박의 종류
    - name: Built_Year
      description: 선박이 건조된 연도
    - name: Class
      description: 선박의 클래스
    - name: Flag
      description: 선박의 국적
