version: 2
sources:
- name: wta_1
  description: wta_1 데이터셋의 테이블 모음
  database: wta_1
  tables:
  - name: rankings
    description: 선수 순위 정보를 담고 있는 테이블
    columns:
    - name: ranking_date
      description: 순위 날짜
    - name: ranking
      description: 선수 순위
    - name: player_id
      description: 선수 고유 ID
    - name: ranking_points
      description: 순위 포인트
    - name: tours
      description: 참여한 투어 수
  - name: players
    description: 선수에 대한 정보 테이블
    columns:
    - name: player_id
      description: 선수의 고유 식별자
    - name: first_name
      description: 선수의 이름
    - name: last_name
      description: 선수의 성
    - name: hand
      description: 선수의 주 손
    - name: birth_date
      description: 선수의 생년월일
    - name: country_code
      description: 선수의 국가 코드
