version: 2
sources:
- name: manufacturer
  description: manufacturer 데이터셋의 테이블 모음
  database: manufacturer
  tables:
  - name: furniture_manufacte
    description: 가구 제조업체에 대한 정보
    columns:
    - name: Manufacturer_ID
      description: 제조업체 고유 식별자
      tests:
      - unique
      - not_null
    - name: Furniture_ID
      description: 가구 고유 식별자
      tests:
      - unique
      - not_null
    - name: Price_in_Dollar
      description: 가구 가격(달러)
      tests:
      - not_null
  - name: furniture
    description: 가구에 대한 정보
    columns:
    - name: Furniture_ID
      description: 가구의 고유 식별자
      tests:
      - unique
      - not_null
    - name: Name
      description: 가구의 이름
      tests:
      - not_null
    - name: Num_of_Component
      description: 구성 요소의 수
      tests:
      - not_null
    - name: Market_Rate
      description: 시장 가격
      tests:
      - not_null
  - name: manufacturer
    description: 제조업체에 대한 정보
    columns:
    - name: Manufacturer_ID
      description: 제조업체 고유 식별자
      tests:
      - unique
      - not_null
    - name: Open_Year
      description: 제조업체 설립 연도
      tests:
      - not_null
    - name: Name
      description: 제조업체 이름
      tests:
      - not_null
    - name: Num_of_Factories
      description: 제조업체의 공장 수
      tests:
      - not_null
    - name: Num_of_Shops
      description: 제조업체의 매장 수
      tests:
      - not_null
