version: 2
sources:
- name: entrepreneur
  description: entrepreneur 데이터셋의 테이블 모음
  database: entrepreneur
  tables:
  - name: entrepreneur
    description: 기업가에 대한 정보
    columns:
    - name: Entrepreneur_ID
      description: 기업가의 고유 식별자
    - name: People_ID
      description: 사람의 고유 식별자
    - name: Company
      description: 기업의 이름
    - name: Money_Requested
      description: 요청된 금액
    - name: Investor
      description: 투자자의 이름
  - name: people
    description: 사람들에 대한 정보
    columns:
    - name: People_ID
      description: 사람의 고유 식별자
    - name: Name
      description: 사람의 이름
    - name: Height
      description: 사람의 키
    - name: Weight
      description: 사람의 몸무게
    - name: Date_of_Birth
      description: 사람의 생년월일
