version: 2
sources:
- name: performance_attendance
  description: performance_attendance 데이터셋의 테이블 모음
  database: performance_attendance
  tables:
  - name: member_attendance
    description: 회원 출석 기록 테이블
    columns:
    - name: Member_ID
      description: 회원 고유 식별자
    - name: Performance_ID
      description: 성능 고유 식별자
    - name: Num_of_Pieces
      description: 작품 수
  - name: performance
    description: 성능 데이터에 대한 설명
    columns:
    - name: Performance_ID
      description: 성능 식별자
    - name: Date
      description: 날짜
    - name: Host
      description: 호스트
    - name: Location
      description: 위치
    - name: Attendance
      description: 참석자 수
  - name: member
    description: 회원 정보를 저장하는 테이블
    columns:
    - name: Member_ID
      description: 회원의 고유 식별자
    - name: Name
      description: 회원의 이름
    - name: Nationality
      description: 회원의 국적
    - name: Role
      description: 회원의 역할
