version: 2
sources:
- name: tracking_orders
  description: tracking_orders 데이터셋의 테이블 모음
  database: tracking_orders
  tables:
  - name: Products
    description: 제품에 대한 정보
    columns:
    - name: product_id
      description: 제품 고유 식별자
      tests:
      - unique
      - not_null
    - name: product_name
      description: 제품 이름
      tests:
      - not_null
    - name: product_details
      description: 제품 세부 정보
      tests:
      - not_null
  - name: Customers
    description: 고객 정보를 담고 있는 테이블
    columns:
    - name: customer_id
      description: 고객의 고유 식별자
      tests:
      - unique
      - not_null
    - name: customer_name
      description: 고객의 이름
      tests:
      - not_null
    - name: customer_details
      description: 고객에 대한 상세 정보
      tests:
      - not_null
  - name: Shipment_Items
    description: 배송 항목에 대한 설명
    columns:
    - name: shipment_id
      description: 배송 식별자
      tests:
      - unique
      - not_null
    - name: order_item_id
      description: 주문 항목 식별자
      tests:
      - not_null
  - name: Order_Items
    description: 주문 항목에 대한 정보
    columns:
    - name: order_item_id
      description: 주문 항목의 고유 식별자
      tests:
      - unique
      - not_null
    - name: product_id
      description: 제품의 고유 식별자
      tests:
      - not_null
    - name: order_id
      description: 주문 고유 식별자
      tests:
      - not_null
    - name: order_item_status
      description: 주문 항목의 상태
      tests:
      - not_null
    - name: order_item_details
      description: 주문 항목에 대한 세부 정보
      tests:
      - not_null
  - name: Invoices
    description: 청구서 테이블
    columns:
    - name: invoice_number
      description: 청구서 번호
      tests:
      - unique
      - not_null
    - name: invoice_date
      description: 청구서 날짜
      tests:
      - not_null
    - name: invoice_details
      description: 청구서 세부사항
      tests:
      - not_null
  - name: Shipments
    description: 배송에 대한 정보
    columns:
    - name: shipment_id
      description: 배송 고유 식별자
      tests:
      - unique
      - not_null
    - name: order_id
      description: 주문 고유 식별자
      tests:
      - not_null
    - name: invoice_number
      description: 송장 번호
      tests:
      - not_null
    - name: shipment_tracking_number
      description: 배송 추적 번호
      tests:
      - not_null
    - name: shipment_date
      description: 배송 날짜
      tests:
      - not_null
    - name: other_shipment_details
      description: 기타 배송 세부 정보
      tests:
      - not_null
  - name: Orders
    description: 주문 테이블에 대한 설명
    columns:
    - name: order_id
      description: 주문 고유 식별자
      tests:
      - unique
      - not_null
    - name: customer_id
      description: 고객 고유 식별자
      tests:
      - not_null
    - name: order_status
      description: 주문 상태
      tests:
      - not_null
    - name: date_order_placed
      description: 주문이 접수된 날짜
      tests:
      - not_null
    - name: order_details
      description: 주문 세부 사항
      tests:
      - not_null
