version: 2
sources:
- name: scientist_1
  description: scientist_1 데이터셋의 테이블 모음
  database: scientist_1
  tables:
  - name: Projects
    description: 프로젝트에 대한 정보
    columns:
    - name: Code
      description: 프로젝트 코드
      tests:
      - unique
      - not_null
    - name: Name
      description: 프로젝트 이름
      tests:
      - not_null
    - name: Hours
      description: 소요 시간
      tests:
      - not_null
  - name: Scientists
    description: 과학자에 대한 정보
    columns:
    - name: SSN
      description: 사회 보장 번호
      tests:
      - unique
      - not_null
    - name: Name
      description: 이름
      tests:
      - not_null
  - name: AssignedTo
    description: 과학자와 프로젝트의 할당 정보를 나타내는 테이블
    columns:
    - name: Scientist
      description: 과학자의 고유 식별자
      tests:
      - unique
      - not_null
    - name: Project
      description: 프로젝트의 식별자
      tests:
      - not_null
