version: 2
sources:
- name: inn_1
  description: inn_1 데이터셋의 테이블 모음
  database: inn_1
  tables:
  - name: Rooms
    description: 객실에 대한 정보
    columns:
    - name: RoomId
      description: 객실의 고유 식별자
    - name: roomName
      description: 객실 이름
    - name: beds
      description: 침대 수
    - name: bedType
      description: 침대 종류
    - name: maxOccupancy
      description: 최대 수용 인원
    - name: basePrice
      description: 기본 가격
    - name: decor
      description: 장식
  - name: Reservations
    description: 예약 정보를 저장하는 테이블
    columns:
    - name: Code
      description: 예약 코드
    - name: Room
      description: 객실 정보
    - name: CheckIn
      description: 체크인 날짜
    - name: CheckOut
      description: 체크아웃 날짜
    - name: Rate
      description: 요금
    - name: LastName
      description: 성
    - name: FirstName
      description: 이름
    - name: Adults
      description: 성인 수
    - name: Kids
      description: 어린이 수
