version: 2
sources:
- name: musical
  description: musical 데이터셋의 테이블 모음
  database: musical
  tables:
  - name: musical
    description: 뮤지컬 테이블에 대한 설명
    columns:
    - name: Musical_ID
      description: 뮤지컬의 고유 식별자
    - name: Name
      description: 뮤지컬의 이름
    - name: Year
      description: 뮤지컬이 발표된 연도
    - name: Award
      description: 수상 내역
    - name: Category
      description: 카테고리
    - name: Nominee
      description: 후보자 이름
    - name: Result
      description: 결과
  - name: actor
    description: 배우에 대한 정보
    columns:
    - name: Actor_ID
      description: 배우의 고유 식별자
    - name: Name
      description: 배우의 이름
    - name: Musical_ID
      description: 뮤지컬의 고유 식별자
    - name: Character
      description: 배우가 연기하는 캐릭터
    - name: Duration
      description: 배우의 활동 기간
    - name: age
      description: 배우의 나이
