version: 2
sources:
- name: gymnast
  description: gymnast 데이터셋의 테이블 모음
  database: gymnast
  tables:
  - name: people
    description: 사람들에 대한 정보
    columns:
    - name: People_ID
      description: 고유 식별자
    - name: Name
      description: 이름
    - name: Age
      description: 나이
    - name: Height
      description: 키
    - name: Hometown
      description: 고향
  - name: gymnast
    description: 체조 선수에 대한 정보
    columns:
    - name: Gymnast_ID
      description: 선수 고유 식별자
    - name: Floor_Exercise_Points
      description: 바닥 운동 점수
    - name: Pommel_Horse_Points
      description: 안장 말 점수
    - name: Rings_Points
      description: 링 점수
    - name: Vault_Points
      description: 도약 점수
    - name: Parallel_Bars_Points
      description: 평행봉 점수
    - name: Horizontal_Bar_Points
      description: 수평봉 점수
    - name: Total_Points
      description: 총 점수
