version: 2
sources:
- name: candidate_poll
  description: candidate_poll 데이터셋의 테이블 모음
  database: candidate_poll
  tables:
  - name: candidate
    description: 후보자에 대한 정보
    columns:
    - name: Candidate_ID
      description: 후보자 고유 식별자
    - name: People_ID
      description: 사람 고유 식별자
    - name: Poll_Source
      description: 여론 조사 출처
    - name: Date
      description: 여론 조사 날짜
    - name: Support_rate
      description: 지지율
    - name: Consider_rate
      description: 고려율
    - name: Oppose_rate
      description: 반대율
    - name: Unsure_rate
      description: 불확실율
  - name: people
    description: 사람들에 대한 정보 테이블
    columns:
    - name: People_ID
      description: 사람의 고유 식별자
    - name: Sex
      description: 성별
    - name: Name
      description: 이름
    - name: Date_of_Birth
      description: 생년월일
    - name: Height
      description: 키
    - name: Weight
      description: 체중
