version: 2
sources:
- name: network_2
  description: network_2 데이터셋의 테이블 모음
  database: network_2
  tables:
  - name: Person
    description: 사람에 대한 정보
    columns:
    - name: name
      description: 이름
    - name: age
      description: 나이
    - name: city
      description: 거주 도시
    - name: gender
      description: 성별
    - name: job
      description: 직업
  - name: PersonFriend
    description: 사람과 친구에 대한 정보
    columns:
    - name: name
      description: 사람의 이름
    - name: friend
      description: 친구의 이름
    - name: year
      description: 연도
