version: 2
sources:
- name: customer_deliveries
  description: customer_deliveries 데이터셋의 테이블 모음
  database: customer_deliveries
  tables:
  - name: Customer_Addresses
    description: 고객 주소 정보를 저장하는 테이블
    columns:
    - name: customer_id
      description: 고객의 고유 식별자
    - name: address_id
      description: 주소의 고유 식별자
    - name: date_from
      description: 주소 유효 시작 날짜
    - name: address_type
      description: 주소 유형
    - name: date_to
      description: 주소 유효 종료 날짜
  - name: Products
    description: 제품에 대한 정보
    columns:
    - name: product_id
      description: 제품의 고유 식별자
    - name: product_name
      description: 제품의 이름
    - name: product_price
      description: 제품의 가격
    - name: product_description
      description: 제품에 대한 설명
  - name: Customers
    description: 고객 정보를 저장하는 테이블
    columns:
    - name: customer_id
      description: 고객의 고유 식별자
    - name: payment_method
      description: 고객의 결제 방법
    - name: customer_name
      description: 고객의 이름
    - name: customer_phone
      description: 고객의 전화번호
    - name: customer_email
      description: 고객의 이메일 주소
    - name: date_became_customer
      description: 고객이 된 날짜
  - name: Actual_Orders
    description: 실제 주문에 대한 정보
    columns:
    - name: actual_order_id
      description: 실제 주문의 고유 식별자
    - name: order_status_code
      description: 주문 상태 코드
    - name: regular_order_id
      description: 정기 주문의 고유 식별자
    - name: actual_order_date
      description: 실제 주문 날짜
  - name: Employees
    description: 직원 정보를 담고 있는 테이블
    columns:
    - name: employee_id
      description: 직원 고유 식별자
    - name: employee_address_id
      description: 직원 주소 고유 식별자
    - name: employee_name
      description: 직원 이름
    - name: employee_phone
      description: 직원 전화번호
  - name: Regular_Order_Products
    description: 정기 주문 제품에 대한 정보
    columns:
    - name: regular_order_id
      description: 정기 주문의 고유 식별자
    - name: product_id
      description: 제품의 고유 식별자
  - name: Delivery_Route_Locations
    description: 배달 경로 위치에 대한 설명
    columns:
    - name: location_code
      description: 위치 코드
    - name: route_id
      description: 경로 식별자
    - name: location_address_id
      description: 위치 주소 식별자
    - name: location_name
      description: 위치 이름
  - name: Trucks
    description: 트럭에 대한 정보
    columns:
    - name: truck_id
      description: 트럭의 고유 식별자
    - name: truck_licence_number
      description: 트럭의 면허 번호
    - name: truck_details
      description: 트럭에 대한 세부 정보
  - name: Regular_Orders
    description: 정기 주문 테이블
    columns:
    - name: regular_order_id
      description: 정기 주문 고유 식별자
    - name: distributer_id
      description: 배급자 고유 식별자
  - name: Addresses
    description: 주소 정보를 저장하는 테이블
    columns:
    - name: address_id
      description: 주소의 고유 식별자
    - name: address_details
      description: 주소 세부 정보
    - name: city
      description: 도시 이름
    - name: zip_postcode
      description: 우편번호
    - name: state_province_county
      description: 주 또는 지방
    - name: country
      description: 국가 이름
  - name: Delivery_Routes
    description: 배달 경로에 대한 설명
    columns:
    - name: route_id
      description: 경로의 고유 식별자
    - name: route_name
      description: 경로의 이름
    - name: other_route_details
      description: 기타 경로 세부사항
  - name: Order_Deliveries
    description: 주문 배달에 대한 정보
    columns:
    - name: location_code
      description: 배달 위치 코드
    - name: actual_order_id
      description: 실제 주문 ID
    - name: delivery_status_code
      description: 배달 상태 코드
    - name: driver_employee_id
      description: 운전사 직원 ID
    - name: truck_id
      description: 트럭 ID
    - name: delivery_date
      description: 배달 날짜
  - name: Actual_Order_Products
    description: 실제 주문 제품에 대한 정보
    columns:
    - name: actual_order_id
      description: 실제 주문의 고유 식별자
    - name: product_id
      description: 제품의 고유 식별자
