version: 2
sources:
- name: orchestra
  description: orchestra 데이터셋의 테이블 모음
  database: orchestra
  tables:
  - name: conductor
    description: 지휘자에 대한 정보
    columns:
    - name: Conductor_ID
      description: 지휘자의 고유 식별자
    - name: Name
      description: 지휘자의 이름
    - name: Age
      description: 지휘자의 나이
    - name: Nationality
      description: 지휘자의 국적
    - name: Year_of_Work
      description: 지휘자의 경력 연수
  - name: show
    description: 쇼에 대한 설명
    columns:
    - name: Show_ID
      description: 쇼의 고유 식별자
    - name: Performance_ID
      description: 공연의 고유 식별자
    - name: If_first_show
      description: 첫 번째 쇼 여부
    - name: Result
      description: 결과에 대한 설명
    - name: Attendance
      description: 참석자 수
  - name: performance
    description: 공연에 대한 정보
    columns:
    - name: Performance_ID
      description: 공연의 고유 식별자
    - name: Orchestra_ID
      description: 오케스트라의 고유 식별자
    - name: Type
      description: 공연의 유형
    - name: Date
      description: 공연 날짜 및 시간
    - name: Official_ratings_(millions)
      description: 공식 평가(백만 단위)
    - name: Weekly_rank
      description: 주간 순위
    - name: Share
      description: 공유 비율
  - name: orchestra
    description: 오케스트라에 대한 설명
    columns:
    - name: Orchestra_ID
      description: 오케스트라의 고유 식별자
    - name: Orchestra
      description: 오케스트라의 이름
    - name: Conductor_ID
      description: 지휘자의 고유 식별자
    - name: Record_Company
      description: 레코드 회사의 이름
    - name: Year_of_Founded
      description: 설립 연도
    - name: Major_Record_Format
      description: 주요 음반 형식
