version: 2
sources:
- name: medicine_enzyme_interaction
  description: medicine_enzyme_interaction 데이터셋의 테이블 모음
  database: medicine_enzyme_interaction
  tables:
  - name: medicine
    description: 약품에 대한 정보
    columns:
    - name: id
      description: 고유 식별자
    - name: name
      description: 질병 이름
    - name: Trade_Name
      description: 상표명
    - name: FDA_approved
      description: FDA 승인 날짜
  - name: enzyme
    description: 효소에 대한 설명
    columns:
    - name: id
      description: 고유 식별자
    - name: name
      description: 이름
    - name: Location
      description: 위치
    - name: Product
      description: 제품
    - name: Chromosome
      description: 염색체
    - name: OMIM
      description: OMIM 번호
    - name: Porphyria
      description: 포르피린증
  - name: medicine_enzyme_interaction
    description: 약물과 효소 간의 상호작용에 대한 정보
    columns:
    - name: enzyme_id
      description: 효소의 고유 식별자
    - name: medicine_id
      description: 약물의 고유 식별자
    - name: interaction_type
      description: 효소와 약물 간의 상호작용 유형
