version: 2
sources:
- name: perpetrator
  description: perpetrator 데이터셋의 테이블 모음
  database: perpetrator
  tables:
  - name: perpetrator
    description: 가해자에 대한 정보
    columns:
    - name: Perpetrator_ID
      description: 가해자의 고유 식별자
      tests:
      - unique
      - not_null
    - name: People_ID
      description: 사람의 고유 식별자
      tests:
      - not_null
    - name: Date
      description: 사건 발생 일시
      tests:
      - not_null
    - name: Year
      description: 사건 발생 연도
      tests:
      - not_null
    - name: Location
      description: 사건 발생 장소
      tests:
      - not_null
    - name: Country
      description: 사건 발생 국가
      tests:
      - not_null
    - name: Killed
      description: 사건에서 사망한 인원 수
      tests:
      - not_null
    - name: Injured
      description: 사건에서 부상당한 인원 수
      tests:
      - not_null
  - name: people
    description: 사람들에 대한 정보
    columns:
    - name: People_ID
      description: 고유 식별자
      tests:
      - unique
      - not_null
    - name: Name
      description: 이름
      tests:
      - not_null
    - name: Height
      description: 신장
      tests:
      - not_null
    - name: Weight
      description: 체중
      tests:
      - not_null
    - name: Home Town
      description: 고향
      tests:
      - not_null
