version: 2
sources:
- name: employee_hire_evaluation
  description: employee_hire_evaluation 데이터셋의 테이블 모음
  database: employee_hire_evaluation
  tables:
  - name: hiring
    description: 채용 관련 정보 테이블
    columns:
    - name: Shop_ID
      description: 상점 고유 식별자
    - name: Employee_ID
      description: 직원 고유 식별자
    - name: Start_from
      description: 시작 날짜 및 시간
    - name: Is_full_time
      description: 정규직 여부
  - name: shop
    description: 상점에 대한 정보
    columns:
    - name: Shop_ID
      description: 상점의 고유 식별자
    - name: Name
      description: 상점의 이름
    - name: Location
      description: 상점의 위치
    - name: District
      description: 상점이 위치한 지역
    - name: Number_products
      description: 상점에서 판매하는 제품의 수
    - name: Manager_name
      description: 상점의 관리자 이름
  - name: evaluation
    description: 직원 평가 테이블
    columns:
    - name: Employee_ID
      description: 직원의 고유 식별자
    - name: Year_awarded
      description: 상여금이 수여된 연도
    - name: Bonus
      description: 수여된 상여금 금액
  - name: employee
    description: 직원 정보를 담고 있는 테이블
    columns:
    - name: Employee_ID
      description: 직원의 고유 식별자
    - name: Name
      description: 직원의 이름
    - name: Age
      description: 직원의 나이
    - name: City
      description: 직원이 거주하는 도시
