version: 2
sources:
- name: cre_Theme_park
  description: cre_Theme_park 데이터셋의 테이블 모음
  database: cre_Theme_park
  tables:
  - name: Photos
    description: 사진 테이블에 대한 설명
    columns:
    - name: Photo_ID
      description: 사진의 고유 식별자
      tests:
      - unique
      - not_null
    - name: Tourist_Attraction_ID
      description: 관광 명소의 고유 식별자
      tests:
      - not_null
    - name: Name
      description: 사진을 찍은 사람의 이름
      tests:
      - not_null
    - name: Description
      description: 사진에 대한 설명
      tests:
      - not_null
    - name: Filename
      description: 사진 파일의 이름
      tests:
      - not_null
    - name: Other_Details
      description: 기타 세부 사항
      tests:
      - not_null
  - name: Museums
    description: 박물관에 대한 정보
    columns:
    - name: Museum_ID
      description: 박물관의 고유 식별자
      tests:
      - unique
      - not_null
    - name: Museum_Details
      description: 박물관에 대한 세부 정보
      tests:
      - not_null
  - name: Tourist_Attraction_Features
    description: 관광 명소의 특징을 나타내는 테이블
    columns:
    - name: Tourist_Attraction_ID
      description: 관광 명소의 고유 식별자
      tests:
      - unique
      - not_null
    - name: Feature_ID
      description: 특징의 고유 식별자
      tests:
      - not_null
  - name: Visitors
    description: 방문자에 대한 정보
    columns:
    - name: Tourist_ID
      description: 관광객의 고유 식별자
      tests:
      - unique
      - not_null
    - name: Tourist_Details
      description: 관광객의 세부 정보
      tests:
      - not_null
  - name: Visits
    description: 방문 기록 테이블
    columns:
    - name: Visit_ID
      description: 방문 고유 식별자
      tests:
      - unique
      - not_null
    - name: Tourist_Attraction_ID
      description: 관광 명소 고유 식별자
      tests:
      - not_null
    - name: Tourist_ID
      description: 관광객 고유 식별자
      tests:
      - not_null
    - name: Visit_Date
      description: 방문 날짜 및 시간
      tests:
      - not_null
    - name: Visit_Details
      description: 방문 세부 사항
      tests:
      - not_null
  - name: Features
    description: 기능에 대한 설명
    columns:
    - name: Feature_ID
      description: 기능의 고유 식별자
      tests:
      - unique
      - not_null
    - name: Feature_Details
      description: 기능에 대한 세부 정보
      tests:
      - not_null
  - name: Locations
    description: 위치 정보를 저장하는 테이블
    columns:
    - name: Location_ID
      description: 위치의 고유 식별자
      tests:
      - unique
      - not_null
    - name: Location_Name
      description: 위치의 이름
      tests:
      - not_null
    - name: Address
      description: 위치의 주소
      tests:
      - not_null
    - name: Other_Details
      description: 위치에 대한 추가 정보
      tests:
      - not_null
  - name: Theme_Parks
    description: 테마파크에 대한 설명
    columns:
    - name: Theme_Park_ID
      description: 테마파크의 고유 식별자
      tests:
      - unique
      - not_null
    - name: Theme_Park_Details
      description: 테마파크에 대한 세부 정보
      tests:
      - not_null
  - name: Staff
    description: 직원 테이블에 대한 설명
    columns:
    - name: Staff_ID
      description: 직원 고유 식별자
      tests:
      - unique
      - not_null
    - name: Tourist_Attraction_ID
      description: 관광 명소 고유 식별자
      tests:
      - not_null
    - name: Name
      description: 직원 이름
      tests:
      - not_null
    - name: Other_Details
      description: 기타 세부 사항
      tests:
      - not_null
  - name: Ref_Attraction_Types
    description: 명소 유형에 대한 참조 테이블
    columns:
    - name: Attraction_Type_Code
      description: 명소 유형 코드
      tests:
      - unique
      - not_null
    - name: Attraction_Type_Description
      description: 명소 유형 설명
      tests:
      - not_null
  - name: Royal_Family
    description: 왕실에 대한 정보
    columns:
    - name: Royal_Family_ID
      description: 왕실 고유 식별자
      tests:
      - unique
      - not_null
    - name: Royal_Family_Details
      description: 왕실에 대한 세부 정보
      tests:
      - not_null
  - name: Street_Markets
    description: 거리 시장에 대한 설명
    columns:
    - name: Market_ID
      description: 시장 고유 식별자
      tests:
      - unique
      - not_null
    - name: Market_Details
      description: 시장 세부 정보
      tests:
      - not_null
  - name: Shops
    description: 상점에 대한 정보
    columns:
    - name: Shop_ID
      description: 상점의 고유 식별자
      tests:
      - unique
      - not_null
    - name: Shop_Details
      description: 상점의 세부 정보
      tests:
      - not_null
  - name: Hotels
    description: 호텔에 대한 정보
    columns:
    - name: hotel_id
      description: 호텔의 고유 식별자
      tests:
      - unique
      - not_null
    - name: star_rating_code
      description: 호텔의 별 등급
      tests:
      - not_null
    - name: pets_allowed_yn
      description: 애완동물 허용 여부
      tests:
      - not_null
    - name: price_range
      description: 가격 범위
      tests:
      - not_null
    - name: other_hotel_details
      description: 기타 호텔 세부 정보
      tests:
      - not_null
  - name: Tourist_Attractions
    description: 관광 명소에 대한 설명
    columns:
    - name: Tourist_Attraction_ID
      description: 관광 명소 고유 식별자
      tests:
      - unique
      - not_null
    - name: Attraction_Type_Code
      description: 관광 명소 유형 코드
      tests:
      - not_null
    - name: Location_ID
      description: 위치 고유 식별자
      tests:
      - not_null
    - name: How_to_Get_There
      description: 가는 방법
      tests:
      - not_null
    - name: Name
      description: 관광 명소 이름
      tests:
      - not_null
    - name: Description
      description: 관광 명소 설명
      tests:
      - not_null
    - name: Opening_Hours
      description: 개장 시간
      tests:
      - not_null
    - name: Other_Details
      description: 기타 세부 사항
      tests:
      - not_null
  - name: Ref_Hotel_Star_Ratings
    description: 호텔 별 등급에 대한 정보
    columns:
    - name: star_rating_code
      description: 별 등급 코드
      tests:
      - unique
      - not_null
    - name: star_rating_description
      description: 별 등급 설명
      tests:
      - not_null
