version: 2
sources:
- name: company_office
  description: company_office 데이터셋의 테이블 모음
  database: company_office
  tables:
  - name: Office_locations
    description: 사무실 위치에 대한 정보
    columns:
    - name: building_id
      description: 건물의 고유 식별자
    - name: company_id
      description: 회사의 고유 식별자
    - name: move_in_year
      description: 입주 연도
  - name: buildings
    description: 건물에 대한 정보
    columns:
    - name: id
      description: 고유 식별자
    - name: name
      description: 건물 이름
    - name: City
      description: 도시 이름
    - name: Height
      description: 건물 높이
    - name: Stories
      description: 층 수
    - name: Status
      description: 건물 상태
  - name: Companies
    description: 회사의 정보에 대한 테이블
    columns:
    - name: id
      description: 고유 식별자
    - name: name
      description: 회사 이름
    - name: Headquarters
      description: 본사 위치
    - name: Industry
      description: 산업 분야
    - name: Sales_billion
      description: 매출 (십억 달러)
    - name: Profits_billion
      description: 이익 (십억 달러)
    - name: Assets_billion
      description: 자산 (십억 달러)
    - name: Market_Value_billion
      description: 시장 가치 (십억 달러)
