version: 2
sources:
- name: network_2
  description: network_2 데이터셋의 테이블 모음
  database: network_2
  tables:
  - name: Person
    description: 사람에 대한 정보
    columns:
    - name: name
      description: 이름
      tests:
      - not_null
    - name: age
      description: 나이
      tests:
      - not_null
    - name: city
      description: 거주 도시
      tests:
      - not_null
    - name: gender
      description: 성별
      tests:
      - not_null
    - name: job
      description: 직업
      tests:
      - not_null
  - name: PersonFriend
    description: 사람과 친구에 대한 정보
    columns:
    - name: name
      description: 사람의 이름
      tests:
      - not_null
    - name: friend
      description: 친구의 이름
      tests:
      - not_null
    - name: year
      description: 연도
      tests:
      - not_null
